parser: "@typescript-eslint/parser"
env:
  browser: true
  es2021: true
extends:
  - airbnb
  - airbnb-typescript
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
overrides:
  - files: ["*.ts", "*.tsx"]
    parserOptions:
      project:
        - tsconfig.json
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
settings:
  import/resolver:
    typescript: true
    node: true
ignorePatterns:
  - "node_modules/"
  - "dist/"
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.d.ts"
rules:
  import/no-extraneous-dependencies: off
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/prefer-default-export: off
  no-eval: error
  no-console: error
  react/function-component-definition:
    - error
    - namedComponents: [arrow-function, function-declaration]
      unnamedComponents: arrow-function
  react/react-in-jsx-scope: off
  react/jsx-props-no-spreading: off
  react/no-unstable-nested-components: off
  react/prop-types: off
  react/require-default-props: off
  react/no-array-index-key: off
  react/destructuring-assignment: off
  consistent-return: off
  prettier/prettier:
    - error
    - endOfLine: auto
