version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build-storybook
  post_build:
    commands:
      - rm -f buildspec.yml
cache:
  paths:
    - "node_modules/**/*"
artifacts:
  files:
    - "**/*"
  base-directory: storybook-static
